name: betteraviation beta
favicon: null
layout_spectrum: 0.6251521985977888
typography_spectrum: 0.24639762309379876
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8e2420'
    - '#ab8e60'
    - '#ffffff'
    - '#685a37'
    - '#dda999'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
